Iter18
daremove/go-metrics-service pull request #18
Opened 2024-04-23 20:14 UTC by daremove

2024-04-23 20:19 UTC, daremove commented on internal/http/serverrouter/server_router.go
> +	r.Use(middleware.NewCompressor(flate.BestSpeed).Handler)
Не знаю как правильно оптимизировать по памяти приложение, из отчета заметил, что заметную часть ресурсов занимает процесс сжатия, поэтому в качестве примера поменял алгоритим

2024-04-24 19:02 UTC, Bazys requested changes
есть парочка вопросов

2024-04-24 19:02 UTC, Bazys commented on internal/storage/memstorage/mem_storage.go
>  func (s *MemStorage) GetGaugeMetric(ctx context.Context, key string) (storage.GaugeMetric, error) {
Параметр функции, `ctx`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `ctx` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-04-24 19:02 UTC, Bazys commented on internal/services/metrics/metrics.go
>  	var result []services.MetricEntry
Преаллоцируй слайс. Тебе известен его будущий размер. как то так:
```go
result := make([]Type, 0, len(gaugeMetrics)+len(counterMetrics))
```
Таки образом повышаем производительность Go-приложения за счет минимизации динамического выделения памяти во время выполнения. Предварительное аллоцирование слайсов в Go может значительно сократить накладные расходы на увеличение слайса по мере добавления элементов, что предполагает выделение новой памяти и копирование существующих элементов в новое пространство памяти.
В Go, когда вы заранее знаете количество элементов, которые будет вмещать слайс, вы можете использовать функцию `make`, чтобы указать его начальную длину и объем. Такая практика особенно полезна для слайсов, размер которых увеличивается по мере выполнения программы, поскольку избавляет Go от необходимости автоматически изменять размер слайса каждый раз, когда в него добавляется элемент после превышения его емкости.
Предварительное аллокация выгодна для производительности, особенно в сценариях с большими массивами данных или высокопроизводительными задачами, потому что она уменьшает количество выделений памяти и связанные с этим затраты на управление памятью, например сборку мусора.
Для более подробного тзучения оптимизации производительности кода Go и управления памятью, включая эффективное использование срезов и функции `make`, посмотри на таких ресурсам, как:
1. [The Impact of Preallocating Slice Memory in Golang (Continued)](https://oilbeater.com/en/2024/03/04/golang-slice-performance-cont/)
2. [Optimize by pre-allocating slice](https://www.programming-books.io/essential/go/optimize-by-pre-allocating-slice-ee6501b596c9446da8b82e4ed35454a6)

2024-04-24 19:02 UTC, Bazys commented on internal/services/metrics/metrics.go
>  	case "gauge":
может строки "gauge", "counter" вынести в константы?

2024-04-30 10:08 UTC, Bazys commented on internal/http/serverrouter/server_router.go
> +	r.Use(middleware.NewCompressor(flate.BestSpeed).Handler)
как минимум преалокация слайса тебе должна была помочь

2024-04-30 10:09 UTC, Bazys approved these changes
Отлично, замечания устранены

2024-04-30 11:29 UTC, merged