Iter20
daremove/go-metrics-service pull request #21
Opened 2024-05-07 21:04 UTC by daremove

2024-05-07 21:23 UTC, Bazys requested changes
Для данной итерации % покрытия тестами должен быть 55%, я у тебя наблюдаю только 39.2%, явно не погрешность измерения

2024-05-07 21:30 UTC, daremove commented
> Для данной итерации % покрытия тестами должен быть 55%, я у тебя наблюдаю только 39.2%, явно не погрешность измерения

Я использую твой скрипт, который показывает 58.1%, как так?

`
#!/bin/sh
go test -v -coverpkg=../... -coverprofile=coverage.out -covermode=count ../...
go tool cover -func coverage.out | grep total | awk '{print $3}'
`

2024-05-16 19:01 UTC, daremove commented
В личке до тебя не дописаться, поэтому добавил еще тестов, на сколько это возможно, получилось так:

`make test`:
<img width="967" alt="image" src="https://github.com/daremove/go-metrics-service/assets/25323878/0ed362e3-2228-4a0c-9ae4-82d4f772e820">

`make test-coverage`:
<img width="1110" alt="image" src="https://github.com/daremove/go-metrics-service/assets/25323878/a8814d48-b8e2-44a7-ae07-0ae80f5cf1c3">

2024-05-19 10:30 UTC, Bazys approved these changes

2024-05-19 10:30 UTC, Bazys commented on internal/services/stats/stats.go
>  	"fmt"
еще в 17 инкрименте проходили про goimports. Подключи проекту на сохранение или гитхук при коммите.

2024-05-19 18:06 UTC, merged